define(function(require) {
  var eight = require('eight/core');
  eight.object3D = require('eight/core/object3D');
  eight.geometry = require('eight/core/geometry');
  eight.material = require('eight/core/material');
  eight.camera = require('eight/cameras/camera');
  eight.perspectiveCamera = require('eight/cameras/perspectiveCamera');
  eight.webGLRenderer = require('eight/renderers/webGLRenderer');
  eight.scene = require('eight/scenes/scene');
  eight.mesh  = require('eight/objects/mesh');
  eight.windowAnimationRunner = require('eight/utils/windowAnimationRunner');
  eight.webGLContextMonitor = require('eight/utils/webGLContextMonitor');
  eight.euclidean3 = require('eight/math/e3ga/euclidean3');
  eight.scalarE3   = require('eight/math/e3ga/scalarE3');
  eight.vectorE3   = require('eight/math/e3ga/vectorE3');
  eight.Conformal3 = require('eight/math/c3ga/Conformal3');
  eight.scalarC3   = require('eight/math/c3ga/scalarC3');
  eight.vectorC3   = require('eight/math/c3ga/vectorC3');
  eight.prismGeometry = require('eight/geometries/prismGeometry');
  eight.meshBasicMaterial = require('eight/materials/meshBasicMaterial');
  eight.meshNormalMaterial = require('eight/materials/meshNormalMaterial');
  return eight;
});
